project_id = "ppewrkvcsjazlgwdtyux"
[functions.process-card-payment]
enabled = true
verify_jwt = true
import_map = "./functions/process-card-payment/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-card-payment/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-card-payment/*.html" ]

[functions.processar-pagamento]
enabled = true
verify_jwt = true
import_map = "./functions/processar-pagamento/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/processar-pagamento/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/processar-pagamento/*.html" ]

[functions.yampi-checkout]
enabled = true
verify_jwt = true
import_map = "./functions/yampi-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/yampi-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/yampi-checkout/*.html" ]

[functions.yampi-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/yampi-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/yampi-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/yampi-webhook/*.html" ]

[functions.process-stripe-split]
enabled = true
verify_jwt = true
import_map = "./functions/process-stripe-split/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-stripe-split/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-stripe-split/*.html" ]

[functions.create-seller-account]
enabled = true
verify_jwt = true
import_map = "./functions/create-seller-account/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-seller-account/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-seller-account/*.html" ]
